# Site settings
title: Quals Reading Notes
description: > # this means to ignore newlines until "baseurl:"
  Notes on readings for my qualifying exams.
baseurl: "/quals" # the subpath of your site, e.g. /blog/
url: "http://jhamrick.github.io" # the base hostname & protocol for your site
twitter_username: jhamrick
github_username:  jhamrick
markdown: kramdown
highlighter: rouge
gems: ['jekyll/scholar']

# Build settings
exclude: ['convert_notebook.sh', 'nbconvert-jekyll-post.tpl', 'nbconvert_utils.py', 'nbconvert_config.py', 'readings', 'Makefile']
include: ['readings.pdf']