# Site settings
title: Quals Reading Notes
description: > # this means to ignore newlines until "baseurl:"
  Notes on readings for my qualifying exams.
baseurl: "/quals" # the subpath of your site, e.g. /blog/
url: "http://jhamrick.github.io" # the base hostname & protocol for your site
twitter_username: jhamrick
github_username:  jhamrick
highlighter: rogue
gems: ['jekyll/scholar']

# Build settings
markdown: kramdown
exclude: ['jekyll-post.py', 'jekyll-post.tpl', 'jekyll_nbconvert.py', 'readings', 'Makefile']
include: ['readings.pdf']